version: '2'
services:
  db:
# mariadbバージョン
# 参考記事 - https://github.com/shinofara/rails_docker_compose/blob/master/docker-compose.yml
    container_name: mariadb
    image: mariadb
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_ROOT_USER: 'root'
      DB_ROOT_PASSWORD: 'mariadb'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    restart: always
# postgresqlバージョン
#    container_name: postgres
#    image: postgres
#    expose:
#      - '5432'
  rails:
    container_name: rails
    build: .
    command: bundle exec unicorn -p 3000 -c config/unicorn.rb
    volumes:
# docker-sync用の設定
      - rails-sync:/var/www/achieve:rw
# 通常用の設定
#      - .:/achieve
    ports:
      - '3000:3000'
    links:
      - db
    restart: always
  nginx:
    container_name: nginx
    build: containers/nginx
    volumes:
      - ./containers_data/nginx:/var/log/nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - rails
    restart: always
# docker-syncで利用されるvolume
volumes:
  rails-sync:
    external: true
