default: &default
# posgresqlバージョン
#  adapter: postgresql
#  encoding: unicode
#  username: postgres
#  host: db
#  pool: 5

# mariadbバージョン
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock
  username: <% ENV['DB_ROOT_USER'] %>
  password: <% ENV['DB_ROOT_PASSWORD'] %>
  # localはdockerコンテナのdbを参照
  host: db

development:
  <<: *default
  # docker-compose.ymlで環境変数を設定
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
  username: root
  password: 23571113
  host: localhost
