default: &default
# posgresqlバージョン
#  adapter: postgresql
#  encoding: unicode
#  username: postgres
#  host: db
#  pool: 5

# mariadbバージョン
  adapter: mysql2
  encoding: utf8
  # docker-compose.ymlで環境変数を設定
  username: <% ENV['DB_ROOT_USER'] %>
  password: <% ENV['DB_ROOT_PASSWORD'] %>
  pool: 5
  # localはdockerコンテナのdbを参照
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: achieve_production
  username: <% ENV['DB_ROOT_USER_PROD'] %>
  password: <% ENV['DB_ROOT_PASSWORD_PROD'] %>
  host: localhost
