default: &default
# posgresqlバージョン
#  adapter: postgresql
#  encoding: unicode
#  username: postgres
#  host: db
#  pool: 5

# mariadbバージョン
  adapter: mysql2
  encoding: utf8
  username: <% ENV['DB_ROOT_USER'] %>
  password: <% ENV['DB_ROOT_PASSWORD'] %>
  pool: 5
  # localはdockerコンテナのdbを参照
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: achieve_development

test:
  <<: *default
  database: achieve_test

production:
  <<: *default
  database: <%= ENV['DATABESE'] %>
  host: localhost
