# 開発環境(twitterはドメインが無いと動かない)
default_sns_keys: &default_sns_keys
  facebook_id: '1692372740987656'
  facebook_secret: '4698f5718fc2dc9632286690a780ff5c'
  twitter_key: 'pZeFVb8ooUrcZSTAONXrsdGyQ'
  twitter_secret: 'aYB7xxNhuAnJXDWAiJ4kyW6YCf31GpbzYnANpfKn0ohajGGcEW'

development:
  secret_key_base: ddd148353a5e8cdb2bc07d8998178d27a47a5c906f061783eab4bc3a03fb32f9a9fe81d06bfca4d69ed948985dc18f1b85becf5e1f4175d695231fa7ee3a699e

test:
  secret_key_base: 8e2ece1b97a34181ec0da0c4b9e135f521307ca4b60b5b4f30217a603f1aee89f8c013de31d942b202d4d43486701b82aec3c74f68bccd94f67bc1d9f7dfaa17

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV['FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
