# 開発環境(twitterはドメインが無いと動かない)
default_sns_keys: &default_sns_keys
  facebook_id: <%= ENV['FACEBOOK_ID'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
